# Generated by Django 2.2.6 on 2019-11-19 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=80)),
                ('valor_servicio', models.IntegerField()),
                ('descripcion_servicio', models.TextField(max_length=200)),
                ('fecha_servicio', models.CharField(choices=[('Primera semana', 'Primera semana'), ('Quincenal', 'Quincenal'), ('Fin de mes', 'Fin de mes')], max_length=100)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=200)),
                ('comuna', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=200)),
                ('tipo_domicilio', models.CharField(choices=[('Fundacion', 'Fundacion'), ('Empresa', 'Empresa'), ('Casa particular', 'Casa particular'), ('Centro educacional', 'Centro educacional')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
