# Generated by Django 2.2.6 on 2019-11-13 21:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente_contraseña'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposervicio',
            name='descripcionServicio',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
