# Generated by Django 2.2.7 on 2019-11-18 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_tiposervicio_descripcionservicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=200)),
                ('comuna', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=200)),
                ('tipo_domicilio', models.CharField(choices=[('Fundacion', 'Fundacion'), ('Empresa', 'Empresa'), ('Casa particular', 'Casa particular'), ('Centro educacional', 'Centro educacional')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='fechaServicio',
            new_name='fecha_servicio',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='tipoServicio',
        ),
        migrations.AddField(
            model_name='servicio',
            name='descripcion_servicio',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='nombre_servicio',
            field=models.CharField(default='default', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='valor_servicio',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='cliente',
        ),
        migrations.AddField(
            model_name='servicio',
            name='cliente',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='TipoServicio',
        ),
    ]
