# Generated by Django 2.2.6 on 2019-11-18 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191118_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='fecha_servicio',
            field=models.CharField(blank=True, choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sabado'), ('Domingo', 'Domingo')], max_length=100, null=True),
        ),
    ]
