# Generated by Django 2.2.6 on 2019-11-19 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191118_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='fecha_servicio',
            field=models.CharField(choices=[('Primera semana', 'Primera semana'), ('Quincenal', 'Quincenal'), ('Fin de mes', 'Fin de mes')], default='default', max_length=100),
            preserve_default=False,
        ),
    ]
